import {
  CARDS,
  SCORE_MAX_SIZE,
  NAVIGATION,
  CATEGORIES,
  FIRST_TABLE_COLS,
  NAVIGATION_INDEX,
  STATISTIC_INDEX,
  CATEGORY_MAX_SIZE,
  NAVIGATION_ACTIVE_LINK_CLASS,
  SORTING_ORDER,
  TIME_INTERVALS,
  STATISTIC_INDICATORS,
} from './const';

export {
  CARDS,
  SCORE_MAX_SIZE,
  NAVIGATION,
  CATEGORIES,
  FIRST_TABLE_COLS,
  NAVIGATION_INDEX,
  STATISTIC_INDEX,
  CATEGORY_MAX_SIZE,
  NAVIGATION_ACTIVE_LINK_CLASS,
  SORTING_ORDER,
  TIME_INTERVALS,
  STATISTIC_INDICATORS,
};
